"""
Build a valid .ipynb notebook for Comify AI IDM-VTON Virtual Try-On.
Uses the OFFICIAL IDM-VTON pipeline from https://github.com/yisol/IDM-VTON
"""
import json

notebook = {
    "nbformat": 4,
    "nbformat_minor": 0,
    "metadata": {
        "colab": {
            "provenance": [],
            "gpuType": "T4",
            "name": "Comify AI - IDM-VTON Virtual Try-On"
        },
        "kernelspec": {"name": "python3", "display_name": "Python 3"},
        "language_info": {"name": "python"},
        "accelerator": "GPU"
    },
    "cells": []
}


def add_md(source_lines):
    notebook["cells"].append({"cell_type": "markdown", "metadata": {}, "source": source_lines})


def add_code(source_lines):
    notebook["cells"].append({"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": source_lines})


# ═══════════════════════════════════════════════════════════════
# CELL 0 — Markdown intro
# ═══════════════════════════════════════════════════════════════
add_md([
    "# Comify AI \u2013 IDM-VTON Virtual Try-On + Size Recommendation (GPU)\n",
    "\n",
    "Uses the **official IDM-VTON pipeline** from [yisol/IDM-VTON](https://github.com/yisol/IDM-VTON).\n",
    "\n",
    "| Task | Model | Source |\n",
    "|------|-------|--------|\n",
    "| Virtual Try-On | **IDM-VTON** (custom TryonPipeline + dual UNet) | [HuggingFace](https://huggingface.co/yisol/IDM-VTON) |\n",
    "| Size Recommendation | **MediaPipe Pose Landmarker** | Google |\n",
    "\n",
    "## Setup\n",
    "1. Runtime \u2192 Change runtime type \u2192 **T4 GPU**\n",
    "2. Run all cells in order\n",
    "3. Paste your **ngrok auth token** in Cell 2\n",
    "4. Copy the printed **ngrok URL** into your backend `.env` or n8n\n",
])

# ═══════════════════════════════════════════════════════════════
# CELL 1 — Install deps + clone IDM-VTON repo
# ═══════════════════════════════════════════════════════════════
add_code([
    "# Cell 1: Install dependencies + clone official IDM-VTON repo\n",
    "import os\n",
    "\n",
    "# Clone official IDM-VTON repo (contains custom pipeline + hacked UNets)\n",
    "if not os.path.exists('/content/IDM-VTON'):\n",
    "    !git clone https://github.com/yisol/IDM-VTON.git /content/IDM-VTON\n",
    "    print('IDM-VTON repo cloned')\n",
    "else:\n",
    "    print('IDM-VTON repo already exists')\n",
    "\n",
    "# Install versions compatible with IDM-VTON's custom UNet (needs PositionNet from diffusers 0.25)\n",
    "!pip install -q huggingface_hub==0.23.5\n",
    "!pip install -q diffusers==0.25.0 transformers==4.36.2 accelerate==0.26.1 safetensors\n",
    "!pip install -q einops  # required by IDM-VTON UNet\n",
    "!pip install -q fastapi uvicorn pyngrok mediapipe Pillow numpy httpx python-multipart\n",
    "!pip install -q torchvision opencv-python-headless\n",
    "!pip install -q bitsandbytes scipy\n",
    "\n",
    "import torch\n",
    'print(f"PyTorch: {torch.__version__}")\n',
    'print(f"CUDA available: {torch.cuda.is_available()}")\n',
    "if torch.cuda.is_available():\n",
    '    print(f"GPU: {torch.cuda.get_device_name(0)}")\n',
    '    print(f"VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")\n',
])

# ═══════════════════════════════════════════════════════════════
# CELL 2 — ngrok auth token
# ═══════════════════════════════════════════════════════════════
add_code([
    "# Cell 2: Set your ngrok auth token\n",
    "# Get a free token at https://dashboard.ngrok.com/get-started/your-authtoken\n",
    'NGROK_AUTH_TOKEN = ""  # <-- paste your token here\n',
    "\n",
    "from pyngrok import ngrok\n",
    "ngrok.set_auth_token(NGROK_AUTH_TOKEN)\n",
    'print("ngrok auth token set")\n',
])

# ═══════════════════════════════════════════════════════════════
# CELL 3 — Load IDM-VTON (official pipeline) + MediaPipe
# ═══════════════════════════════════════════════════════════════
add_code([
    "# Cell 3: Load official IDM-VTON pipeline + MediaPipe Pose\n",
    "\n",
    "import sys, io, os, base64, time, gc, cv2\n",
    "import numpy as np\n",
    "import torch\n",
    "from PIL import Image, ImageFilter, ImageDraw\n",
    "from transformers import CLIPImageProcessor, CLIPVisionModelWithProjection, AutoTokenizer, CLIPTextModel, CLIPTextModelWithProjection\n",
    "from diffusers import DDPMScheduler, AutoencoderKL\n",
    "\n",
    "# Add IDM-VTON repo to path so we can import the custom modules\n",
    "sys.path.insert(0, '/content/IDM-VTON')\n",
    "from src.tryon_pipeline import StableDiffusionXLInpaintPipeline as TryonPipeline\n",
    "from src.unet_hacked_garmnet import UNet2DConditionModel as UNet2DConditionModel_ref\n",
    "from src.unet_hacked_tryon import UNet2DConditionModel\n",
    "\n",
    "# ───────────────────────────────────\n",
    "# 3a. Load IDM-VTON model components\n",
    "#     Load to CPU first, then use\n",
    "#     enable_model_cpu_offload() to\n",
    "#     avoid OOM on T4 (15.6 GB VRAM)\n",
    "# ───────────────────────────────────\n",
    'MODEL_ID = "yisol/IDM-VTON"\n',
    "DTYPE = torch.float16\n",
    "\n",
    'print("Loading IDM-VTON components to CPU (then GPU-offloaded at inference)...")\n',
    'print("(First run downloads ~6 GB of model weights)")\n',
    "\n",
    "# Noise scheduler\n",
    "noise_scheduler = DDPMScheduler.from_pretrained(MODEL_ID, subfolder=\"scheduler\")\n",
    'print("  [1/7] Scheduler loaded")\n',
    "\n",
    "# VAE — load to CPU\n",
    "vae = AutoencoderKL.from_pretrained(MODEL_ID, subfolder=\"vae\", torch_dtype=DTYPE)\n",
    'print("  [2/7] VAE loaded")\n',
    "\n",
    "# Main UNet (tryon) — hacked architecture, load to CPU\n",
    "unet = UNet2DConditionModel.from_pretrained(MODEL_ID, subfolder=\"unet\", torch_dtype=DTYPE)\n",
    'print("  [3/7] UNet (tryon) loaded")\n',
    "\n",
    "# Garment encoder UNet — load to CPU\n",
    "unet_encoder = UNet2DConditionModel_ref.from_pretrained(MODEL_ID, subfolder=\"unet_encoder\", torch_dtype=DTYPE)\n",
    'print("  [4/7] UNet (garment encoder) loaded")\n',
    "\n",
    "# CLIP image encoder — load to CPU\n",
    "image_encoder = CLIPVisionModelWithProjection.from_pretrained(MODEL_ID, subfolder=\"image_encoder\", torch_dtype=DTYPE)\n",
    "clip_processor = CLIPImageProcessor.from_pretrained(MODEL_ID, subfolder=\"image_encoder\")\n",
    'print("  [5/7] CLIP image encoder loaded")\n',
    "\n",
    "# Text encoders + tokenizers (SDXL dual) — load to CPU\n",
    'tokenizer_one = AutoTokenizer.from_pretrained(MODEL_ID, subfolder="tokenizer", use_fast=False)\n',
    'tokenizer_two = AutoTokenizer.from_pretrained(MODEL_ID, subfolder="tokenizer_2", use_fast=False)\n',
    "text_encoder_one = CLIPTextModel.from_pretrained(MODEL_ID, subfolder=\"text_encoder\", torch_dtype=DTYPE)\n",
    "text_encoder_two = CLIPTextModelWithProjection.from_pretrained(MODEL_ID, subfolder=\"text_encoder_2\", torch_dtype=DTYPE)\n",
    'print("  [6/7] Text encoders loaded")\n',
    "\n",
    "# Assemble pipeline on CPU\n",
    "pipe = TryonPipeline.from_pretrained(\n",
    "    MODEL_ID,\n",
    "    unet=unet,\n",
    "    vae=vae,\n",
    "    feature_extractor=clip_processor,\n",
    "    image_encoder=image_encoder,\n",
    "    scheduler=noise_scheduler,\n",
    "    text_encoder=text_encoder_one,\n",
    "    text_encoder_2=text_encoder_two,\n",
    "    tokenizer=tokenizer_one,\n",
    "    tokenizer_2=tokenizer_two,\n",
    "    torch_dtype=DTYPE,\n",
    ")\n",
    "pipe.unet_encoder = unet_encoder\n",
    "\n",
    "# Use CPU offloading — only moves each model to GPU when needed,\n",
    "# then moves it back to CPU. Prevents OOM on T4.\n",
    "pipe.enable_model_cpu_offload()\n",
    'print("  [7/7] Pipeline assembled with CPU offloading")\n',
    "\n",
    "# Free references (pipeline owns them now)\n",
    "del vae, unet, image_encoder, text_encoder_one, text_encoder_two\n",
    "gc.collect()\n",
    "if torch.cuda.is_available():\n",
    "    torch.cuda.empty_cache()\n",
    "\n",
    'print("IDM-VTON pipeline ready!")\n',
    "\n",
    "# ───────────────────────────────────\n",
    "# 3b. MediaPipe Pose Landmarker\n",
    "# ───────────────────────────────────\n",
    "import mediapipe as mp\n",
    "from mediapipe.tasks.python import vision, BaseOptions\n",
    "\n",
    'POSE_MODEL_URL = "https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_heavy/float16/latest/pose_landmarker_heavy.task"\n',
    'POSE_MODEL_PATH = "/tmp/pose_landmarker_heavy.task"\n',
    "\n",
    "if not os.path.exists(POSE_MODEL_PATH):\n",
    "    import urllib.request\n",
    '    print("Downloading pose landmarker model...")\n',
    "    urllib.request.urlretrieve(POSE_MODEL_URL, POSE_MODEL_PATH)\n",
    "\n",
    "pose_options = vision.PoseLandmarkerOptions(\n",
    "    base_options=BaseOptions(model_asset_path=POSE_MODEL_PATH),\n",
    "    running_mode=vision.RunningMode.IMAGE,\n",
    "    min_pose_detection_confidence=0.5,\n",
    "    min_tracking_confidence=0.5,\n",
    ")\n",
    "pose_landmarker = vision.PoseLandmarker.create_from_options(pose_options)\n",
    'print("MediaPipe PoseLandmarker loaded!")\n',
    "\n",
    "\n",
    "# ───────────────────────────────────\n",
    "# 3c. Helper functions\n",
    "# ───────────────────────────────────\n",
    "def decode_b64(data: str) -> Image.Image:\n",
    '    if "," in data:\n',
    '        data = data.split(",", 1)[1]\n',
    '    return Image.open(io.BytesIO(base64.b64decode(data))).convert("RGB")\n',
    "\n",
    "def encode_b64(img: Image.Image) -> str:\n",
    "    buf = io.BytesIO()\n",
    '    img.save(buf, format="JPEG", quality=90)\n',
    "    return base64.b64encode(buf.getvalue()).decode()\n",
    "\n",
    "\n",
    "# ───────────────────────────────────\n",
    "# 3d. Pose image + agnostic mask\n",
    "#     (replaces DensePose/OpenPose\n",
    "#      with MediaPipe for simplicity)\n",
    "# ───────────────────────────────────\n",
    "\n",
    "# MediaPipe pose connections for drawing pose image\n",
    "POSE_CONNECTIONS = [\n",
    "    (11, 12), (11, 13), (13, 15), (12, 14), (14, 16),  # arms\n",
    "    (11, 23), (12, 24), (23, 24),                        # torso\n",
    "    (23, 25), (25, 27), (24, 26), (26, 28),              # legs\n",
    "    (0, 11), (0, 12),                                     # head to shoulders\n",
    "]\n",
    "\n",
    "def create_pose_image(landmarks, w, h):\n",
    '    """Create an OpenPose-style pose image from MediaPipe landmarks."""\n',
    '    pose_img = Image.new("RGB", (w, h), (0, 0, 0))\n',
    "    draw = ImageDraw.Draw(pose_img)\n",
    "    def lm_pt(idx):\n",
    "        lm = landmarks[idx]\n",
    "        return (int(lm.x * w), int(lm.y * h))\n",
    "    # Draw connections\n",
    "    for (i, j) in POSE_CONNECTIONS:\n",
    "        try:\n",
    "            p1, p2 = lm_pt(i), lm_pt(j)\n",
    "            draw.line([p1, p2], fill=(255, 255, 255), width=3)\n",
    "        except:\n",
    "            pass\n",
    "    # Draw keypoints\n",
    "    for idx in [0, 11, 12, 13, 14, 15, 16, 23, 24, 25, 26, 27, 28]:\n",
    "        try:\n",
    "            pt = lm_pt(idx)\n",
    "            draw.ellipse([pt[0]-4, pt[1]-4, pt[0]+4, pt[1]+4], fill=(255, 0, 0))\n",
    "        except:\n",
    "            pass\n",
    "    return pose_img\n",
    "\n",
    "\n",
    "def create_agnostic_mask(person_img, landmarks):\n",
    '    """Create agnostic mask covering the torso + upper arms region."""\n',
    "    w, h = person_img.size\n",
    '    mask = Image.new("L", (w, h), 0)\n',
    "    draw = ImageDraw.Draw(mask)\n",
    "    def lm_pt(idx):\n",
    "        lm = landmarks[idx]\n",
    "        return (int(lm.x * w), int(lm.y * h))\n",
    "    ls = lm_pt(11)   # left shoulder\n",
    "    rs = lm_pt(12)   # right shoulder\n",
    "    lh = lm_pt(23)   # left hip\n",
    "    rh = lm_pt(24)   # right hip\n",
    "    le = lm_pt(13)   # left elbow\n",
    "    re = lm_pt(14)   # right elbow\n",
    "    sw = abs(rs[0] - ls[0])\n",
    "    pad = int(sw * 0.4)\n",
    "    # Main torso polygon\n",
    "    poly = [\n",
    "        (rs[0] - pad, rs[1] - int(sw * 0.2)),   # above right shoulder\n",
    "        (ls[0] + pad, ls[1] - int(sw * 0.2)),   # above left shoulder\n",
    "        (ls[0] + pad, lh[1] + int(sw * 0.15)),  # below left hip\n",
    "        (rs[0] - pad, rh[1] + int(sw * 0.15)),  # below right hip\n",
    "    ]\n",
    "    draw.polygon(poly, fill=255)\n",
    "    # Also mask upper arms\n",
    "    arm_w = int(sw * 0.2)\n",
    "    for shoulder, elbow in [(ls, le), (rs, re)]:\n",
    "        arm_poly = [\n",
    "            (shoulder[0] - arm_w, shoulder[1]),\n",
    "            (shoulder[0] + arm_w, shoulder[1]),\n",
    "            (elbow[0] + arm_w, elbow[1]),\n",
    "            (elbow[0] - arm_w, elbow[1]),\n",
    "        ]\n",
    "        draw.polygon(arm_poly, fill=255)\n",
    "    mask = mask.filter(ImageFilter.GaussianBlur(radius=15))\n",
    "    return mask\n",
    "\n",
    "\n",
    "def create_agnostic_image(person_img, mask):\n",
    '    """Create agnostic image (person with masked region grayed out)."""\n',
    "    agnostic = person_img.copy()\n",
    "    gray = Image.new(\"RGB\", person_img.size, (128, 128, 128))\n",
    "    agnostic = Image.composite(gray, agnostic, mask)\n",
    "    return agnostic\n",
    "\n",
    "\n",
    "# ───────────────────────────────────\n",
    "# 3e. IDM-VTON inference function\n",
    "# ───────────────────────────────────\n",
    "def run_idm_vton(person_img, garment_img, landmarks, num_steps=30, guidance_scale=2.0, seed=42):\n",
    '    """Run the OFFICIAL IDM-VTON TryonPipeline."""\n',
    "    w, h = person_img.size\n",
    "    target_h, target_w = 1024, 768\n",
    "\n",
    "    # Resize inputs\n",
    "    person_resized = person_img.resize((target_w, target_h), Image.LANCZOS)\n",
    "    garment_resized = garment_img.resize((target_w, target_h), Image.LANCZOS)\n",
    "\n",
    "    # Create pose image from MediaPipe landmarks\n",
    "    pose_img = create_pose_image(landmarks, w, h).resize((target_w, target_h), Image.LANCZOS)\n",
    "\n",
    "    # Create agnostic mask and agnostic image\n",
    "    mask = create_agnostic_mask(person_img, landmarks)\n",
    "    mask_resized = mask.resize((target_w, target_h), Image.LANCZOS)\n",
    "    agnostic_img = create_agnostic_image(person_resized, mask_resized.convert(\"L\"))\n",
    "\n",
    "    # Garment mask (all white = use full garment)\n",
    '    garment_mask = Image.new("L", (target_w, target_h), 255)\n',
    "\n",
    "    # Prepare CLIP image for garment encoding\n",
    "    clip_image = clip_processor(images=garment_resized, return_tensors=\"pt\").pixel_values\n",
    "\n",
    "    # Prompt\n",
    '    prompt = "model is wearing a garment"\n',
    '    negative_prompt = "monochrome, lowres, bad anatomy, worst quality, low quality"\n',
    "\n",
    "    # Encode prompt\n",
    "    with torch.no_grad():\n",
    "        (\n",
    "            prompt_embeds,\n",
    "            negative_prompt_embeds,\n",
    "            pooled_prompt_embeds,\n",
    "            negative_pooled_prompt_embeds,\n",
    "        ) = pipe.encode_prompt(\n",
    "            prompt,\n",
    "            num_images_per_prompt=1,\n",
    "            do_classifier_free_guidance=True,\n",
    "            negative_prompt=negative_prompt,\n",
    "        )\n",
    "\n",
    "        # Encode prompt for garment encoder\n",
    '        prompt_c = "a photo of a garment"\n',
    '        negative_prompt_c = "monochrome, lowres, bad anatomy, worst quality, low quality"\n',
    "        (\n",
    "            prompt_embeds_c,\n",
    "            _,\n",
    "            _,\n",
    "            _,\n",
    "        ) = pipe.encode_prompt(\n",
    "            prompt_c,\n",
    "            num_images_per_prompt=1,\n",
    "            do_classifier_free_guidance=False,\n",
    "            negative_prompt=negative_prompt_c,\n",
    "        )\n",
    "\n",
    "    generator = torch.Generator(device=\"cpu\").manual_seed(seed)\n",
    "\n",
    "    # Run the pipeline\n",
    "    with torch.no_grad():\n",
    "        result = pipe(\n",
    "            prompt_embeds=prompt_embeds,\n",
    "            negative_prompt_embeds=negative_prompt_embeds,\n",
    "            pooled_prompt_embeds=pooled_prompt_embeds,\n",
    "            negative_pooled_prompt_embeds=negative_pooled_prompt_embeds,\n",
    "            num_inference_steps=num_steps,\n",
    "            generator=generator,\n",
    "            strength=1.0,\n",
    "            pose_img=pose_img.convert(\"RGB\"),\n",
    "            text_embeds_cloth=prompt_embeds_c,\n",
    "            cloth=garment_resized.convert(\"RGB\"),\n",
    "            mask_image=mask_resized,\n",
    "            image=(person_resized, agnostic_img),  # (person, agnostic) tuple\n",
    "            ip_adapter_image=clip_image,\n",
    "            guidance_scale=guidance_scale,\n",
    "            height=target_h,\n",
    "            width=target_w,\n",
    "        ).images[0]\n",
    "\n",
    "    # Resize back to original\n",
    "    result = result.resize((w, h), Image.LANCZOS)\n",
    "\n",
    "    if torch.cuda.is_available():\n",
    "        torch.cuda.empty_cache()\n",
    "        gc.collect()\n",
    "\n",
    "    return result\n",
    "\n",
    "\n",
    "# ───────────────────────────────────\n",
    "# 3f. Size recommendation (MediaPipe)\n",
    "# ───────────────────────────────────\n",
    "SIZE_CHART = {\n",
    '    "XS": {"chest": (76, 84), "waist": (60, 68)},\n',
    '    "S":  {"chest": (84, 92), "waist": (68, 76)},\n',
    '    "M":  {"chest": (92, 100), "waist": (76, 84)},\n',
    '    "L":  {"chest": (100, 108), "waist": (84, 92)},\n',
    '    "XL": {"chest": (108, 116), "waist": (92, 100)},\n',
    '    "XXL": {"chest": (116, 130), "waist": (100, 115)},\n',
    "}\n",
    "\n",
    "def estimate_measurements(landmarks, w, h):\n",
    "    def lm(idx):\n",
    "        l = landmarks[idx]\n",
    "        return np.array([l.x * w, l.y * h])\n",
    "    ls, rs = lm(11), lm(12)\n",
    "    lh, rh = lm(23), lm(24)\n",
    "    nose = lm(0)\n",
    "    la, ra = lm(27), lm(28)\n",
    "    shoulder_px = np.linalg.norm(ls - rs)\n",
    "    hip_px = np.linalg.norm(lh - rh)\n",
    "    body_height_px = np.linalg.norm(nose - (la + ra) / 2)\n",
    "    scale = 170.0 / max(body_height_px, 1)\n",
    "    shoulder_cm = round(shoulder_px * scale, 1)\n",
    "    chest_cm = round(shoulder_cm * 2.6, 1)\n",
    "    waist_cm = round(((shoulder_px + hip_px) / 2) * scale * 2.3, 1)\n",
    "    hip_cm = round(hip_px * scale * 2.8, 1)\n",
    "    height_cm = round(body_height_px * scale, 1)\n",
    '    return {"shoulders": shoulder_cm, "chest": chest_cm, "waist": waist_cm,\n',
    '            "hips": hip_cm, "height": height_cm}\n',
    "\n",
    "def recommend_size(measurements):\n",
    '    chest = measurements.get("chest", 92)\n',
    '    waist = measurements.get("waist", 78)\n',
    '    best_size, best_score = "M", float("inf")\n',
    "    for size, ranges in SIZE_CHART.items():\n",
    '        score = abs(chest - sum(ranges["chest"]) / 2) + abs(waist - sum(ranges["waist"]) / 2)\n',
    "        if score < best_score:\n",
    "            best_score, best_size = score, size\n",
    "    return best_size\n",
    "\n",
    "def detect_pose_and_measure(img):\n",
    '    """Full pose detection + measurement pipeline."""\n',
    "    arr = np.array(img)\n",
    "    mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=arr)\n",
    "    results = pose_landmarker.detect(mp_image)\n",
    "    if not results.pose_landmarks or len(results.pose_landmarks) == 0:\n",
    "        return None\n",
    "    landmarks = results.pose_landmarks[0]\n",
    "    w, h = img.size\n",
    "    MP_NAMES = {\n",
    '        0: "nose", 11: "left_shoulder", 12: "right_shoulder",\n',
    '        13: "left_elbow", 14: "right_elbow", 15: "left_wrist", 16: "right_wrist",\n',
    '        23: "left_hip", 24: "right_hip", 25: "left_knee", 26: "right_knee",\n',
    '        27: "left_ankle", 28: "right_ankle",\n',
    "    }\n",
    "    ls, rs = landmarks[11], landmarks[12]\n",
    "    lh, rh = landmarks[23], landmarks[24]\n",
    "    fe_lm = [\n",
    '        {"name": "neck", "x": round((ls.x + rs.x) / 2, 4), "y": round((ls.y + rs.y) / 2 - 0.02, 4)},\n',
    '        {"name": "left_waist", "x": round((ls.x + lh.x) / 2, 4), "y": round((ls.y + lh.y) / 2, 4)},\n',
    '        {"name": "right_waist", "x": round((rs.x + rh.x) / 2, 4), "y": round((rs.y + rh.y) / 2, 4)},\n',
    "    ]\n",
    "    for idx, name in MP_NAMES.items():\n",
    "        lm_val = landmarks[idx]\n",
    '        fe_lm.append({"name": name, "x": round(lm_val.x, 4), "y": round(lm_val.y, 4)})\n',
    "    measurements = estimate_measurements(landmarks, w, h)\n",
    "    size = recommend_size(measurements)\n",
    "    sizes = list(SIZE_CHART.keys())\n",
    "    sidx = sizes.index(size) if size in sizes else 2\n",
    '    nose_vis = getattr(landmarks[0], "visibility", 0.95)\n',
    "    return {\n",
    '        "bodyDetected": True,\n',
    '        "confidence": round(min(max(nose_vis, 0.85), 0.99), 4),\n',
    '        "bodyMeasurements": measurements,\n',
    '        "poseDetection": {"detected": True, "pose": "standing", "landmarks": fe_lm},\n',
    '        "recommendedSize": size,\n',
    '        "clothingFitPrediction": {\n',
    '            "tops": size,\n',
    '            "bottoms": sizes[min(sidx + 1, len(sizes) - 1)] if measurements.get("hips", 0) > 100 else size,\n',
    '            "dresses": size,\n',
    "        },\n",
    '        "_raw_landmarks": landmarks,\n',
    "    }\n",
    "\n",
    'print("\\nAll models and functions ready!")\n',
])

# ═══════════════════════════════════════════════════════════════
# CELL 4 — FastAPI server + ngrok tunnel
# ═══════════════════════════════════════════════════════════════
add_code([
    "# Cell 4: Start FastAPI server + ngrok tunnel\n",
    "\n",
    "import threading\n",
    "import uvicorn\n",
    "from fastapi import FastAPI, HTTPException\n",
    "from fastapi.middleware.cors import CORSMiddleware\n",
    "from pydantic import BaseModel\n",
    "\n",
    'colab_app = FastAPI(title="Comify AI - IDM-VTON Colab Server")\n',
    "colab_app.add_middleware(\n",
    '    CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"]\n',
    ")\n",
    "\n",
    "class TryOnRequest(BaseModel):\n",
    "    person_image: str       # base64\n",
    "    garment_image: str      # base64\n",
    '    category: str = "tops"\n',
    "    num_steps: int = 30\n",
    "    guidance_scale: float = 2.0\n",
    "    seed: int = 42\n",
    "\n",
    "class SizeRequest(BaseModel):\n",
    "    person_image: str       # base64\n",
    "\n",
    '@colab_app.get("/health")\n',
    "def health():\n",
    '    gpu_name = torch.cuda.get_device_name(0) if torch.cuda.is_available() else "none"\n',
    '    return {"status": "ok", "gpu": torch.cuda.is_available(), "gpu_name": gpu_name, "model": "IDM-VTON-official"}\n',
    "\n",
    '@colab_app.post("/generate-tryon")\n',
    "def tryon(req: TryOnRequest):\n",
    '    """Official IDM-VTON virtual try-on."""\n',
    "    t0 = time.time()\n",
    "    person_img = decode_b64(req.person_image)\n",
    "    garment_img = decode_b64(req.garment_image)\n",
    "\n",
    "    # Detect pose\n",
    "    pose_data = detect_pose_and_measure(person_img)\n",
    "    if not pose_data:\n",
    '        raise HTTPException(422, "No person detected. Upload a clear full-body photo.")\n',
    '    raw_landmarks = pose_data.pop("_raw_landmarks")\n',
    "\n",
    "    # Run IDM-VTON\n",
    '    print(f"Running IDM-VTON ({req.num_steps} steps, guidance={req.guidance_scale})...")\n',
    "    result_img = run_idm_vton(\n",
    "        person_img, garment_img, raw_landmarks,\n",
    "        num_steps=req.num_steps,\n",
    "        guidance_scale=req.guidance_scale,\n",
    "        seed=req.seed,\n",
    "    )\n",
    "    duration = round(time.time() - t0, 2)\n",
    '    print(f"Try-on complete in {duration}s")\n',
    "\n",
    "    return {\n",
    '        "try_on_image": encode_b64(result_img),\n',
    '        "recommended_size": pose_data["recommendedSize"],\n',
    '        "bodyMeasurements": pose_data["bodyMeasurements"],\n',
    '        "confidence": pose_data["confidence"],\n',
    '        "inference_time_s": duration,\n',
    "    }\n",
    "\n",
    '@colab_app.post("/size-recommendation")\n',
    "def size_rec(req: SizeRequest):\n",
    '    """MediaPipe Pose-based size recommendation."""\n',
    "    person_img = decode_b64(req.person_image)\n",
    "    pose_data = detect_pose_and_measure(person_img)\n",
    "    if not pose_data:\n",
    '        raise HTTPException(422, "No person detected. Upload a clear full-body photo.")\n',
    '    pose_data.pop("_raw_landmarks", None)\n',
    "    return pose_data\n",
    "\n",
    "# Start server\n",
    "def run_server():\n",
    '    uvicorn.run(colab_app, host="0.0.0.0", port=8000)\n',
    "\n",
    "thread = threading.Thread(target=run_server, daemon=True)\n",
    "thread.start()\n",
    "time.sleep(3)\n",
    "\n",
    "# Create ngrok tunnel\n",
    "public_url = ngrok.connect(8000)\n",
    "print()\n",
    'print("=" * 60)\n',
    'print("  COMIFY AI COLAB SERVER IS LIVE!")\n',
    'print("  Pipeline: Official IDM-VTON TryonPipeline")\n',
    "if torch.cuda.is_available():\n",
    '    print(f"  GPU: {torch.cuda.get_device_name(0)}")\n',
    'print("=" * 60)\n',
    "print()\n",
    'print(f"  Public URL: {public_url}")\n',
    'print(f"  COLAB_ENDPOINT={public_url}")\n',
    "print()\n",
    'print(f"  GET  {public_url}/health")\n',
    'print(f"  POST {public_url}/generate-tryon")\n',
    'print(f"  POST {public_url}/size-recommendation")\n',
    'print("=" * 60)\n',
])

# ═══════════════════════════════════════════════════════════════
# CELL 5 — Keep alive + self-test
# ═══════════════════════════════════════════════════════════════
add_code([
    "# Cell 5: Keep alive + quick test\n",
    "\n",
    "import requests\n",
    "\n",
    "try:\n",
    '    r = requests.get("http://localhost:8000/health")\n',
    '    print(f"Health check: {r.json()}")\n',
    "except Exception as e:\n",
    '    print(f"Health check failed: {e}")\n',
    "\n",
    'print("\\nColab server running. This cell keeps the session alive.")\n',
    'print("Press the stop button to shut down.\\n")\n',
    "while True:\n",
    "    time.sleep(60)\n",
    "    print(f\"[alive] {time.strftime('%H:%M:%S')}\", end=\" | \", flush=True)\n",
])

# ═══════════════════════════════════════════════════════════════
# Write the notebook file
# ═══════════════════════════════════════════════════════════════
out_path = r"c:\Users\Admin\Downloads\ComifyAiProject-main\ComifyAiProject-main\backend\colab\Comify_AI_Virtual_TryOn_Colab.ipynb"

with open(out_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

# Validate
with open(out_path, "r") as f:
    data = json.load(f)
print(f"OK - {len(data['cells'])} cells, nbformat {data['nbformat']}.{data['nbformat_minor']}")
for i, c in enumerate(data["cells"]):
    t = c["cell_type"]
    n = len(c["source"])
    print(f"  Cell {i}: {t} ({n} lines)")
